from google_trans_new  import  google_translator
import pyttsx3
# print(google_trans_new.LANGUAGES)

LTr = input("Type the text you want to translate in any language >>>> ")
translator = google_translator()  

print("Choose the Language you want the text to be translated in")
print("1. Afrikaans - (af)")
print("2. Albanian - (sq)")
print("3. Amharic - (am)")
print("4. Arabic - (ar)")
print("5. Armenian - (hy)")
print("6. Azerbaijani - (az)")
print("7. Basque - (eu)")
print("8. Belarusian - (be)")
print("9. Bengali - (bn)")
print("10. Bosnian - (bs)")
print("11. Bulgarian - (bg)")
print("12. Catalan - (ca)")
print("13. Cebuano - (ceb)")
print("14. Chichewa - (ny)")
print("15. Chinese Simplified - (zh-cn)")
print("16. Chinese Traditional - (zh-tw)")
print("17. Corsican - (co)")
print("18. Croatian - (hr)")
print("19. Czech - (cs)")
print("20. Danish - (da)")
print("21. Dutch - (nl)")
print("22. English - (en)")
print("23. Esperanto - (eo)")
print("24. Estonian - (et)")
print("25. Filipino - (tl)")
print("26. Finnish - (fi)")
print("27. French - (fr)")
print("28. Frisian - (fy)")
print("29. Galician - (gl)")
print("30. Georgian - (ka)")
print("31. German - (de)")
print("32. Greek - (el)")
print("33. Gujarati - (gu)")
print("34. Haitian Creole - (ht)")
print("35. Hausa - (ha)")
print("36. Hawaiian - (haw)")
print("37. Hebrew - (iw)")
print("38. Hindi - (hi)")
print("39. Hmong - (hmn)")
print("40. Hungarian - (hu)")
print("41. Icelandic - (is)")
print("42. Igbo - (ig)")
print("43. Indonesian - (id)")
print("44. Irish - (ga)")
print("45. Italian - (it)")
print("46. Japanese - (ja)")
print("47. Javanese - (jw)")
print("48. Kannada - (kn)")
print("49. Kazakh - (kk)")
print("50. Khmer - (km)")
print("51. Korean - (ko)")
print("52. Kurdish or Kurmanji - (ku)")
print("53. Kyrgyz - (ky)")
print("54. Lao - (lo)")
print("55. Latin - (la)")
print("56. Latvian - (lv)")
print("57. Lithunian - (lt)")
print("58. Luxembourgish - (lb)")
print("59. Macedonian - (mk)")
print("60. Malagasy - (mg)")
print("61. Malay - (ms)")
print("62. Malayalam - (ml)")
print('63. Maltese - (mt)')
print("64. Maori - (mi)")
print("65. Marathi - (mr)")
print("66. Mongolian - (mn)")
print("67. Burmese - (my)")
print("68. Nepali - (ne)")
print("69. Norwegian - (no)")
print("70. Pashto - (ps)")
print("71. Persian - (fa)")
print("72. Polish - (pl)")
print("73. Portugese - (pt)")
print("74. Punjabi - (pa)")
print("75. Romanian - (ro)")
print("76. Russian - (ru)")
print("77. Samoan - (sm)")
print("78. Scots Gaelic - (gd)")
print("79. Serbian - (sr)")
print("80. Sesotho - (st)")
print("81. Shona - (sn)")
print("82. Sindhi - (sd)")
print("83. Sinhala - (si)")
print("84. Slovak - (sk)")
print("85. Slovenian - (sl)")
print("86. Somali - (so)")
print("87. Spanish - (es)")
print("88. Sundanese - (su)")
print("89. Swahili - (sw)")
print("90. Swedish - (sv)")
print("91. Tajik - (tg)")
print("92. Tamil - (ta)")
print("93. Telugu - (te)")
print("94. Thai - (th)")
print("95. Turkish - (tr)")
print("96. Ukranian - (uk)")
print("97. Urdu - (ur)")
print("98. Uzbek - (uz)")
print("99. Vietnamese - (vi)")
print("100. Welsh - (cy)")
print("101. Xhosa - (xh)")
print("102. Yiddish - (yi)")
print("103. Yoruba - (yo)")
print("104. Zulu - (zu)")
print("Choose one language and then type the character in the language's bracket below")
Lang = input(">>>> ")
translated_text = translator.translate(LTr,lang_tgt=Lang)
print("Translation = "+translated_text)

a = pyttsx3.init()
a.setProperty("language",Lang)
a.say(translated_text)
a.runAndWait()
print("Translation = "+translated_text)
